services:
  db:
    image: postgres:16
    container_name: taavonyar_db
    environment:
      POSTGRES_DB: taavonyar
      POSTGRES_USER: taavonyar
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - taavonyar_pgdata:/var/lib/postgresql/data

  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: taavonyar_web
    environment:
      DJANGO_DEBUG: "1"
      DJANGO_SECRET_KEY: "dev-secret-key-change-later"
      DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1"
      POSTGRES_DB: taavonyar
      POSTGRES_USER: taavonyar
      POSTGRES_PASSWORD: admin
      POSTGRES_HOST: db
      POSTGRES_PORT: "5432"
      
    volumes: []
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  taavonyar_pgdata:
